openapi: '3.0.3'
info:
  title: Petstore API
  description: A sample Pet Store API for testing the OpenAPI validator
  version: '1.0.0'
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://petstore.example.com/v1
    description: Production server
  - url: http://localhost:3000/v1
    description: Development server

tags:
  - name: pets
    description: Operations related to pets
  - name: store
    description: Operations related to the store

paths:
  /pets:
    get:
      operationId: listPets
      summary: List all pets
      description: Returns a list of all pets in the store
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of pets to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      operationId: createPet
      summary: Create a new pet
      description: Adds a new pet to the store
      tags:
        - pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /pets/{petId}:
    get:
      operationId: getPetById
      summary: Get a pet by ID
      description: Returns a single pet by its ID
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
            format: int64
          example: 123
      responses:
        '200':
          description: A single pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      operationId: updatePet
      summary: Update a pet
      description: Updates an existing pet
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '200':
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      operationId: deletePet
      summary: Delete a pet
      description: Deletes a pet from the store
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Pet deleted successfully
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /store/inventory:
    get:
      operationId: getInventory
      summary: Get store inventory
      description: Returns the current inventory status
      tags:
        - store
      responses:
        '200':
          description: Inventory status
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                example:
                  available: 10
                  pending: 5
                  sold: 3

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the pet
          example: 123
        name:
          type: string
          description: Name of the pet
          example: Fluffy
        tag:
          type: string
          description: Optional tag for the pet
          example: dog
        status:
          type: string
          enum:
            - available
            - pending
            - sold
          description: Status of the pet in the store
          example: available
        createdAt:
          type: string
          format: date-time
          description: When the pet was added to the store

    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the pet
          minLength: 1
          maxLength: 100
          example: Fluffy
        tag:
          type: string
          description: Optional tag for the pet
          example: dog
        status:
          type: string
          enum:
            - available
            - pending
            - sold
          default: available

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
          example: 404
        message:
          type: string
          description: Error message
          example: Pet not found

  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - apiKey: []
  - bearerAuth: []
